### ISSUE TITLE
Stuck on 'click here'

### ISSUE THREAD

**Issue by Jsanderson444** [parsiad/nexus-autodl#2] opened 2022-07-03 00:07 UTC
OS: Windows 10
Display resolution: 1920 x 1080
Refresh rate: 144 mon1 60 mon2
Monitors: 2 (All 1920 x 1080)
Wabbajack v2.5.3.24

The program is getting stuck at the Click_here routine.  I believe the sleep timing is the issue, where the program is scraping the screen during the ~250 ms when the "click here to continue" page is being shown.  However, that page quickly disappears but the autodl keeps trying to click it and gets stuck.    This occurs randomly, but on average every 10-20 downloads.

A solution would be to attempt to run the click_here routine once, then scrape to see if it's still present. 

07/02/2022 08:57:38 PM [INFO] Clicking on slow_download at coordinates x=1074.330566 y=676.271545
07/02/2022 08:57:38 PM [INFO] No matches found
07/02/2022 08:57:38 PM [INFO] Sleeping for 2.708454 seconds
07/02/2022 08:57:41 PM [INFO] No matches found
07/02/2022 08:57:41 PM [INFO] Sleeping for 2.477630 seconds
07/02/2022 08:57:44 PM [INFO] No matches found
07/02/2022 08:57:44 PM [INFO] Sleeping for 4.000639 seconds
07/02/2022 08:57:49 PM [INFO] Clicking on slow_download at coordinates x=1074.330566 y=676.271545
07/02/2022 08:57:49 PM [INFO] No matches found
07/02/2022 08:57:49 PM [INFO] Sleeping for 3.227662 seconds
07/02/2022 08:57:53 PM [INFO] No matches found
07/02/2022 08:57:53 PM [INFO] Sleeping for 0.111719 seconds
07/02/2022 08:57:54 PM [INFO] No matches found
07/02/2022 08:57:54 PM [INFO] Sleeping for 4.565793 seconds
07/02/2022 08:57:59 PM [INFO] No matches found
07/02/2022 08:57:59 PM [INFO] Sleeping for 3.807614 seconds
07/02/2022 08:58:04 PM [INFO] Clicking on click_here at coordinates x=532.894836 y=425.698151
07/02/2022 08:58:04 PM [INFO] No matches found
07/02/2022 08:58:04 PM [INFO] Sleeping for 1.366361 seconds
07/02/2022 08:58:06 PM [INFO] Clicking on click_here at coordinates x=532.894836 y=425.698151
07/02/2022 08:58:06 PM [INFO] No matches found
07/02/2022 08:58:06 PM [INFO] Sleeping for 3.735259 seconds

**Comment by nihiluis** [comment] 2022-07-10 16:44
Did you check that the slow download button looks similar to the slow_download.png file in the templates directory?

**Comment by SirenBrink** [comment] 2022-07-18 18:44
it seems to want to click on the "Choose download" text

Also there is no templates directory. Nexus AutoDL is a standalone executable.

**Comment by parsiad** [comment] 2022-10-07 21:05
Duplicate of #5.

**Closed as completed by parsiad** 2022-10-07 21:05 UTC
