### ISSUE TITLE
click_here loop

### ISSUE THREAD

**Issue by JustAMerePleb** [parsiad/nexus-autodl#4] opened 2022-08-12 17:21 UTC
Hi your program work great but its often capture the "click here" button and will stuck in a loop.
![lw_f54Z9ddpK4](https://user-images.githubusercontent.com/70328953/184408746-6ed758ef-4a63-47ec-b50d-ec334cd3032c.png)

As long as the "click here" is not captured, the program wouldn't stuck in a loop.
![lw_KXozP3VYqB](https://user-images.githubusercontent.com/70328953/184410025-2ab8a665-c33f-4093-8cd6-454fbf096c2f.png)

Maybe "click here" keep looping because it fail to click "click here"(since it usually only appear like 0.5s-1s for me) and the program won't capture the new "slow download" image.

**Comment by lawfulrocky** [comment] 2022-08-17 12:35
i am having the same problem

**Comment by SirenBrink** [comment] 2022-09-03 20:49
Try Wabbajack Automagic

It has a img folder where you can easily crop an image of the download button and correct the default one (Win + Shift + S)

**Comment by parsiad** [comment] 2022-10-07 21:04
Duplicate of #5.

**Closed as completed by parsiad** 2022-10-07 21:04 UTC
